title: Reality Studios
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://realitystudios.xyz"
collections:
 - authors
paginate: 5
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-gist
github: [metadata]
sass:
  sass-dir: _sass
  style: compressed
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  